### ISSUE TITLE
tb should not be activated on json pages.

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#259]
Basically any page ending with .json (and possible parameters). Apparently it injects some html at the bottom of those pages in some cases. 

```
 [08:28:55] <Helzibah> Gambit: yup, it's a notification thingy that's just not showing right because json
 [08:29:19] <Helzibah> it seems very confused because I'm logged out :P
```

Probably doesn't do any damage but it is cleaner if toolbox just doesn't activate there.

**Comment by Dakta** [comment]
I confirm that TB does load and inject stuff into the HTML of .json pages (ace-editor related stylesheets get injected into `<head>`), but it doesn't affect the displayed JSON as far as I can tell.
Toolbox proper doesn't load because of the not logged-in check in tbstorage: https://github.com/creesch/reddit-moderator-toolbox/blob/master/tbstorage.js#L83

    if (!$("form.logout input[name=uh]").val()) return; // not logged in.

If we want to be more specific, we can do this:

    // stop everything and don't load on .json or .json-html API pages
    pageExtention = location.pathname.match(/(?:([^:\/?#]+):)?(?:\/\/([^\/?#]*))?([^?#]*\.(?:json|json-html))(?:\?([^#]*))?(?:#(.*))?/);
    // if (pageExtention) {
    //     return;
    // }

And put it somewhere where it will keep libs/ace.js from being injected. Or we have to manually control whether libs/ace.js is loaded.
