### ISSUE TITLE
[UN] paginate usernotes

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#375]
The time has come.  

Between schema 5 and the caching work in 3.0, usernotes cannot be optimized any more than they are.  There is no hope left for user note expansion short of pagination.  We'll have to move to /w/usernotes/pageID, using a similar system to reddit's before/after.

**Comment by agentlame** [comment]
I'm going to close this.  A: it wouldn't work since reddit now makes special considerations for /w/usernotes, but also the space increase plus S6 make this less of an issue for some time.

**Comment by psdtwk** [comment]
Saw "paginate usernotes" in my inbox. got excited.
Then I saw "won't fix" and was heartbroken. 

It was an emotional rollercoaster.

**Comment by Dakta** [comment]
Just as a note for the future, if we ever come back to this: we should consider pagination to also be some form of index, if possible, so that we don't make multiple requests unless necessary. An example of this could be having the first page for usernames starting with a-p and the second page q-z, 0-9. Yes i know the odds of that being helpful are slim, but if we decide to go with pagination we should consider the possibility of subs ending up with a shit-ton of pages, and need to plan to optimize that from the start.
