### ISSUE TITLE
Karmadecay link?

### ISSUE THREAD

**Issue by travisnewman** [creesch/reddit-moderator-toolbox#485]
Hey creesch and the team,

Would it be possible to add a "karmadecay" link to the list of links below a post (share, save, hide, report, etc) to check the post on Karma Decay? I imagine it would be a simple addition, just linking to karmadecay.com/r/subreddit/rest-of-the-url. 

I swear I used to have an extension that did this at one time, but I can't find it. Thanks!

**Comment by creesch** [comment]
I am not entirely sure this falls into the domain of toolbox since it is rather specific. I am thinking it might even be something more suitable for RES.

**Comment by travisnewman** [comment]
Specific how? I imagine it would help mods more than the general populace, giving a quick way to check it. 

With the advent of .gifv and the like (which karmadecay supports) the actual karmadecay extension is less useful since you can't just right click the gifv to check like you can with normal images. If that makes sense.

BUT I can imagine it being something RES might also do, so I'll ask there as well :)

**Comment by creesch** [comment]
Well, specific to image subreddits.

**Comment by travisnewman** [comment]
That's not entirely true. We use it on /r/space a lot. But that's a fair
point.

Allthefoxes turned down the RES feature request.

On Saturday, March 7, 2015, creesch <notifications@github.com> wrote:

> Well, specific to image subreddits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creesch/reddit-moderator-toolbox/issues/485#issuecomment-77712317>
> .
>


--

**Comment by Dakta** [comment]
Since when has /u/allthefoxes been in a position to decide RES project direction? Have you asked @andytuba about it?

**Comment by andytuba** [comment]
@allthefoxes is developing a sense for what we've turned down in the past, but @honestbleeps and I still keep an eye on things. (a little slowly, though, since we've both been busy). 

karmadecay integration is something we've said no to in the past, specifically checking every post on a page, because of the number of API calls, the clutter, and the fact that other extensions already existed. probably some other reasons, too. 

I'm still loath to add Yet Another Button to the post button list, but once I get an overflow menu or post info/action hover pop-up set up, then i would reconsider for RES. however, I'm not yet convinced of the utility of having it in res. 

it might be useful for some mods, so toolbox could be appropriate.

**Comment by allthefoxes** [comment]
Wow @Dakta, rude. <3

I don't decide anything with RES, but I do enough QA and hang around enough to know the general stance of andytuba and honestbleeps on stuff.

That said, I do need to be a bit more careful with my wording in the future.

**Comment by travisnewman** [comment]
Sorry for the confusion folks. I did think that @allthefoxes comment was coming from a place of authority, but now I see that wasn't his intention.

@andytuba the extension doesn't work for everything karmadecay does, thus my frustration with it and looking to RES and toolbox for help.

**Comment by allthefoxes** [comment]
Sorry @travisnewman ! I'll be more careful with my words in the future!

**Comment by Dakta** [comment]
@allthefoxes I'm sorry, can you forgive me?

> I'm still loath to add Yet Another Button to the post button list, but once I get an overflow menu or post info/action hover pop-up set up, then i would reconsider for RES.

@andytuba I agree. Give a shout if/when you get a clean implementation for RES, because we've got at least two damn buttons for Toolbox and we'd like to make them Go Away™. I don't like the idea of hiding anything behind a dropdown menu in that button list, though, and I don't think you do either... Perhaps there's some clever way to detect multi-line overflow and accordion nicely without upsetting subreddit CSS.

For Toolbox, something that we might consider would be a JavaScript snippets module, which would allow mods to define (for themselves and for mod teams at the subreddit level) custom JavaScript macros to be executed from buttons in that toolbar, or something. That way we might simplify a couple current features, such as the Stattit/RedditMetrics Tab, into example snippets, and things like this KarmaDecay button could be added that way as well.

**Comment by creesch** [comment]
> For Toolbox, something that we might consider would be a JavaScript snippets module, which would allow mods to define (for themselves and for mod teams at the subreddit level) custom JavaScript macros to be executed from buttons in that toolbar

This is already possible, you can add javascript bookmarklets to the toolbar.

**Comment by Dakta** [comment]
Well well... So it is.

**Comment by agentlame** [comment]
...sigh.  I mean, we could stuff it into the mod button, maybe.  But I don't see enough people needing this.  

In SFWP (~100 subreddits) we need to use GRIS and TinEye on almost every post to check for image source, so we install the relevant extensions.  I could easily add that functionality to TB and it'd be justified... but it doesn't belong in TB, it belongs in a Karmadecay extension.

Sorry, I'm closing this.

**Comment by agentlame** [comment]
>This is already possible, you can add javascript bookmarklets to the modbar.

FTFY
