### ISSUE TITLE
Moderator achievements

### ISSUE THREAD

**Issue by psdtwk** [creesch/reddit-moderator-toolbox#490]
> [Because nothing motivates mods to work harder than popups.](http://i.imgur.com/dr7S42q.png)

Bonus wish: a leaderboard, so we can compare stats to each other. 

[reddit post for reference](http://www.reddit.com/r/toolbox/comments/3175jp/request_mod_achievements_because_nothing/)

**Comment by agentlame** [comment]
Feature meeting log:


5:31 PM <•agentlame> lmao
5:32 PM <•psdtwk> It's a fucking great idea!
5:32 PM <•agentlame> It would have to be checking the mod logs of all your subs in the background.
5:32 PM <•agentlame> Unless we are willing to settle for relative activity, by which TB just keeps its own track of actions. 
5:33 PM <•psdtwk>  you could save gets by pulling /r/mod/about/log
5:33 PM <•agentlame> lol... dude that page hasn't loaded for me in over two years.
5:33 PM <•agentlame> Do u even power mod?
5:33 PM <•psdtwk> oh shit. Haha I forget you and mwm have that problem.
5:34 PM <•psdtwk> You don't get achievements. <--- problem solved ;)
5:34 PM <•agentlame> http://i.imgur.com/YFJaWxX.png
5:35 PM <•agentlame> That's fair.
5:35 PM <•agentlame> I'd only ever get the ban one anyways.
5:35 PM <•psdtwk> How about we compromise. If /r/mod works, then use it, otherwise use local information.
5:36 PM <•psdtwk> Because there's nothing like doubling the amount of work for a silly enhancement request.
5:36 PM <Gustavobc> achievement get: break /r/mod/about/log
5:36 PM <•agentlame> Too much engineering for a novelty feature.  It can just use local saved stats. 
5:36 PM <•agentlame> Gustavobc: brilliant!
5:36 PM <•agentlame> SOLVED!
5:37 PM <Gustavobc> !

**Comment by creesch** [comment]
Eh

**Comment by alienfromEuropa** [comment]
You can make it easier. Run the Moderation Log Matrix call. For that set of time, popups of some achievements of the results. Doesn't need to run all the time in the background.

**Comment by agentlame** [comment]
I mod 400 subreddits.  Which does it run on and when?

**Comment by psdtwk** [comment]
@alienfromEuropa You're suggesting toolbox calculates the achievements when the user goes to the mod log page and generates the matrix?

**Comment by alienfromEuropa** [comment]
It's the only easy solution I can think of if it is too complicated to run in the background. 

Otherwise, maybe time the mod log to be checked at different times automatically, instead of being run continuously. Like, maybe once every 24 hours?

**Comment by alienfromEuropa** [comment]
Could also shorten the achievement time from a month to a week, for a faster check. Just an idea.

**Comment by psdtwk** [comment]
@alienfromeuropa see https://github.com/creesch/reddit-moderator-toolbox/issues/490#issuecomment-89426905

**Comment by Dakta** [comment]
I think this is somewhat out of the scope of Toolbox features. At best, we have to hit the API up for the modlogs of every subreddit a user moderates, individually because /r/mod isn't guaranteed to work (I assume @spladug and @bsimpson63 know about this?), and then generate a combined modlog report. For many of our core userbase, that'll take a long-ass time to do all the requests within the API ratelimit.

If there's a desire for mod stats and leaderboards, I think the best approach is to write a bot and get mod teams to use it.

**Comment by bsimpson63** [comment]
@Dakta what's the issue with /r/mod?

**Comment by agentlame** [comment]
>because /r/mod isn't guaranteed to work (I assume @spladug and @bsimpson63 know about this?)

I *highly* doubt they care too much.  I mean it only affects me, MwM and maybe a few more people.  Plus, when you mod enough subs to break it, it's pretty useless.

...wow, github comments are real-time.  @bsimpson63 /r/mod/about/log 503's if you mod like 400 subreddits.

**Comment by psdtwk** [comment]
@Dakta agentlame, way up there already said it's impractical to use the modlog, and that if this were done, it would be generated by local actions and _not_ the log.

**Comment by Dakta** [comment]
@bsimpson63 `/r/mod/about/log` does not load for a number of power moderators such as /u/agentlame, /u/ManWithoutModem, and I assume many others with similarly large sub counts:

> 5:33 PM <•psdtwk> you could save gets by pulling /r/mod/about/log  
5:33 PM <•agentlame> lol... dude that page hasn't loaded for me in over two years.

**Comment by creesch** [comment]
ok, I am just going to say it. I think that this entire thing is silly and a waste of time and resources if we tried to implement it.

**Comment by ChadWarden** [comment]
I hope you guys go though with this.

**Comment by agentlame** [comment]
Ok, I'm just gonna say it: moderating reddit is a thankless shit show.   Sometimes fun is worth the effort in its own right.

**Comment by creesch** [comment]
That is true, however I don't think that "Oh I need to ban one more person to get that achievement" is the right incentive we are looking for to make it more fun.

**Comment by creesch** [comment]
Also, from irc: 

   <creesch> if you really want it you'd probably are better of using a bot that puts the achievements on a wiki page.
   <creesch> That way you can make it a per subreddit thing for subs that are into that stuff
   <psdtwk> I'll ask requestabot about it

Making a bot do it and create an achievement wiki basically solves most issues with performance.

**Comment by TheEnigmaBlade** [comment]
Achievements in progress, but the framework was put in place starting with 7393ee24d51fff5f94afdf2f2c0d2a632ccd3f6e.
