### ISSUE TITLE
Find something proper to issue for the nuke icon.

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#491]
Because this is ugly as fuck and clutters up an area that already has too much shit put into it.

**Comment by psdtwk** [comment]
:feelsgood:

**Comment by agentlame** [comment]
This.  Also we don't have a license to that icon.

**Comment by creesch** [comment]
http://i.imgur.com/6fiytZr.jpg


This is a mockup I made a while ago. Alternatively it would start with usernotes so you can see the last note.

**Comment by agentlame** [comment]
Interesting.

**Comment by andytuba** [comment]
Yalls should totally use the high voltage Unicode character: ⚡

**Comment by Dakta** [comment]
@agentlame If you want to talk license to use stuff, we didn't have license to use the nuke script code to begin with, did we? At least the user who created the icon implied a generous license for anyone to use it.

I am in favor of moving the nuke button into `.flat-list.buttons` and not having an icon. I like the intent of @creesch's proposal, but items in `.flat-list.buttons` should be specific to the individual `thing`, not general for the user like user notes or user history. I think those should stick up in the header after the username, because they go with the username and not the comment/submission.

**Comment by agentlame** [comment]
@Dakta I have no clue if djimbob *created* that icon.  Do you?

**Comment by Dakta** [comment]
Nope, another user did: https://www.reddit.com/r/modclub/comments/13amg8/one_of_the_raskscience_secret_weapons_is/c72tq0t (his links are dead, but I assume that djimbob didn't change the icon after he said he was using 3).

**Comment by agentlame** [comment]
Fair 'nuff.  Buuuut, it's still super fucking ugly. :)

**Comment by Dakta** [comment]
I agree, and the current implementation competes with the AskScience nuke UserScript. Can I just put "nuke" as a new item in the `.flat-list.buttons` next to "mod"?

**Comment by creesch** [comment]
yeah, seems the most clean solution until we find something better.
