### ISSUE TITLE
[libs] update and test all the libs we use in next major release

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#510]
Mostly I'm thinking jquery, but might as well make sure all are upto date.

**Comment by creesch** [comment]
jquery doesn't really need updating unless newer version do security fixes imho. 
Doesn't hurt to go over it though.

**Comment by creesch** [comment]
Actually jquery has been done for EDGE, syntax highlighting has been recently replaced as well.

That leaves pako.js which we use for usernotes compression and which seems to have been modified by enigma to be used within an extension.  Which is still working and I am not going to touch for now. 

Since the next major release is the overhaul for the reddit redesign I am closing this issue for now and possibly make a seperate issue for pako.
