### ISSUE TITLE
make macro dropdown a javascript dropdown

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#526]
Hell, it's worth a shot.

If not, we'll let it go until 3.2... but it'd be awesome for 3.1!

**Comment by creesch** [comment]
Hrm... I am not sure why we would do that to be honest? The the html dropdowns in this instance are simple and work pretty well. The places where I have implemented the javascript versions is where it was not possible to use html dropdowns. 

What would be the benefit of implementing them for macros?

**Comment by creesch** [comment]
oh and I forgot, the javascript dropdowns currently don't work with keyboard navigation.  

tl;dr I am not a fan but if we decide to implement them it will be 3.2 if we want macros out of beta AND make our release date.

**Comment by agentlame** [comment]
Simple and good reason: dat variable size.

**Comment by creesch** [comment]
Hrm... I am still not convinced considering the amount of trouble that comes with them. 

Let me think about it for a bit, for macros something might be possible that requires less code. To do it properly it will be 3.2 though,

**Comment by agentlame** [comment]
What trouble?   RES uses them for their macros and it's not an issue in the slightest. 

If you don't want to do it yourself then just say that.

**Comment by creesch** [comment]
They do indeed, which are specifically aimed at macros and not generic. Making them generic means accounting for a whole lot of situations in regards to positioning, custom stylesheets, etc. 

as I said

> Let me think about it for a bit, for macros something might be possible that requires less code.  

Basically I am open to implementing them if you want them, however considering that you want to release on friday it means we have very little time to test it and make sure there are no stupid bugs. Since you just moved macros out of beta I think 3.2 is more realistic. That's all.

**Comment by agentlame** [comment]
@creesch ayy bb... can this be 4reel now?

**Comment by creesch** [comment]
I am sorry but have to push this to 3.3, things I want it to be able to do in order to replace native html dropdowns: 

- arrow selection. 
- enter to select
- something else I probably should have written down when I was thinking about this. 

I also need to think about styling them, the ones we have now have a slightly different function since the ones we have now also serve as search result dropdown. It makes sense to give the ones that are only a dropdown somewhat different styling, proper UX.

**Comment by agentlame** [comment]
Isn't metrics tab just a dropdown?

**Comment by creesch** [comment]
One I am not entirely happy with (try clicking outside the text) which has hyperlinks in it. Good call though, whenever I do this that one should be converted properly.

**Comment by agentlame** [comment]
Should we just hold 3.2?   You seem rather displeased with these extremely mundane dropdowns.  

This issue is clearly blocking since it requires a new petty reason to push with each release.

**Comment by creesch** [comment]
I am just saying I won't have time to do it properly this release... Not in the way I would like it to. I am terribly sorry I don't have more time on my hands.

**Comment by agentlame** [comment]
This is a 10 for me.  I assume that you'd be OK with using the dropdown from metrics tab until a suitable replacement is found?

If so,  I'll fix this on Monday in time for 3.2

**Comment by creesch** [comment]
Sure, if we can't reasonably talk about stuff anymore go right ahead. 

> agentlame> I was kinda leaving those in if anyone wanted to knock them out.  

I am just saying that I won't for this release since as I repeatedly pointed out the native html versions simply work better (yes they are less "pretty") as far as UX goes and every time I try to mention it you go completely apeshit about it because... well fuck if I know. 

So yeah, sure go ahead and do this if you really care so fucking much about it that you have to act like a little petulant child every time I try to neutrally discuss things. 

Let me know when 3.2 is done, I'll make sure to push it to the stores.

**Comment by agentlame** [comment]
I said it was a 10?   Normally we have these discussions in private, but you decided that isn't a venue for **private fucking discussions** anymore.


So now we'll do it here, in the most public way known to man because **you** decided we can't bitch at one another in private anymore.  

This shit is on you, not me.

**Comment by creesch** [comment]
> This is a 10 for me. I assume that you'd be OK with using the dropdown from metrics tab until a suitable replacement is found?

Yeah like this isn't the ultimate example of a passive aggressive note on the fridge? *"Let's first yell several at creesch for trying to be reasonable about it, then yell at him some more when he objects to the yelling calling him a child in the process. But that is ok because it is in private..."*. 

Should I also begin about fucking double standards? **[this shit isn't private either](https://github.com/creesch/reddit-moderator-toolbox/commit/544c95ed70666ef18718639324f497b30c559cae)**... 

I am fucking done with getting yelled at every time I find some time to work on toolbox or comment at issues.

**Comment by agentlame** [comment]
Your persecution complex is amazing.  

Look, we agreed to a simple voting system between on another.  The one time I use it, you bitch.  

You know damned well I wanted this fixed *before* 3.1.  But you keep pushing it for moronic reasons.  It's a fucking JS dropdown... *you* don't even need to fix it, the only reason it's still open is because you'll only accept *your* fix.

As for the rest of this nonsense, **you** decided we can't have reasonable discussions in private.  No one else did that.

**Comment by TheEnigmaBlade** [comment]
*sigh*

If you're going to bitch at each other, do it elsewhere and stop stinking the project up. I'm getting tired of this.

**Comment by creesch** [comment]
As I said, let me know when 3.2 is done. I'll push it to the stores. 

As far as this issue goes, well whatever floats your boat. All I see is one person just taking the time to write out his thoughts on something and one other person typing oneliners and saying things that basically say "If you don't want to do it..."  (While ignoring the reasons given) and "pushing it for moronic reasons" (while still having ignored all reasons given so far). 
Wouldn't it be much easier to say "Look creesch, I just don't value your opinion anymore"? Instead of this bullshit where you get angry every time I try to discuss something were we aren't in agreement.

**Comment by agentlame** [comment]
@creesch I don't know who deleted the comments (they were correct), but can you just edit your's down to the issue, delete this comment and take the other shit to PMs, like we use to?

**Comment by creesch** [comment]
http://www.bulgaria-web-developers.com/projects/javascript/selectbox/

https://github.com/marcj/jquery-selectBox

Referencing these to look into later to implement this in a way that makes both of us happy.

**Comment by agentlame** [comment]
This was fixed with the new button style.
