### ISSUE TITLE
bring better buttons out of beta

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#576]
- ~~resolve/test issues with mod-save (are there issues?)~~
 - finish support for ignoreOn and approveOn
 - make ignoreOn to be only a BB feature (it's in both QT and BB)
 - migrate the QT setting for ignoreOn to BB
 - hide unfinished/non-working features
 - ~~remove/approve confirmation remover~~

**Comment by TheEnigmaBlade** [comment]
* hide unfinished/non-working features
  + remove/approve confirmation remover

Ideally I would just like to get it working because it's a feature I really miss (I used to have my own userscript to do it), but I've struggled so much with jquery on() working sometimes and not working other times. :angry:

**Comment by agentlame** [comment]
@TheEnigmaBlade I would bet good money it's the same issue we see here: https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/removalreasons.js#L149 / https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/removalreasons.js#L173

It has been a long time, but there is a reason for that.  jQuery has some weird issue with some types of click events.

**Comment by TheEnigmaBlade** [comment]
It's been a while since I've tried to figure it out, but the problem lies with the use of `on()` to detect if a remove/approve button is clicked. This is what it does currently, which used to work when in its own userscript:

    $body.on('click', '.flat-list > .remove-button', function () { ... });

IIRC, the event is never triggered, even though the exact same format is also used to check for click events on the distinguish button and big approve/ignore reports buttons in the same module.

**Comment by agentlame** [comment]
But surly this is something we resolved in Queue Tools. I can't imagine that we have have a working solution that doesn't work in a different context.

**Comment by Dakta** [comment]
Queue Tools uses the `.big-mod-buttons .pretty-button` and doesn't actually have click events on the other ones.
