### ISSUE TITLE
Add option to the user history button to see what % of a user's posts are in "blackboxed/reclassified" subreddits

### ISSUE THREAD

**Issue by empyrical** [creesch/reddit-moderator-toolbox#586]
Idea first worked out here:

https://www.reddit.com/r/defaultmods/comments/3djkpc/lets_talk_content_ama_rannouncements_now_up/ct8ch4i?context=3

This is all conjecture on how such a thing could work, as it's not live yet. But spez said here that reddit gold will be disabled on those communities:

https://www.reddit.com/r/announcements/comments/3djjxw/lets_talk_content_ama/ct7cfmq?context=3

So the way this feature could hypothetically work and detect if the comment/submission is in a reclassified sub, is to see if the user has the ability to gold it. If the user doesn't, then it's probably a "reclassified" sub

**Comment by agentlame** [comment]
I'm not sure I'm comfortable with such a feature.   People are free to *use* toolbox however they'd like, but I don't like the idea of features with an agenda.

It's not too much work to just read the names of the subs someone comments in.

**Comment by empyrical** [comment]
It's live now, and since the "quarantined" subreddits have to be opted in one by one (there's no option to opt-in temporarily to viewing all quarantined subreddits) I don't think this feature can work at all anyways.

**Comment by Dakta** [comment]
This is an important consideration. Quarantines make checking user history rather challenging, as explained in this submission: https://www.reddit.com/r/ModSupport/comments/3fyiwv/major_issue_due_to_quarantines_user_histories_are/

The ability to gild stuff is a moot point since, without explicitly opting in to every quarantined subreddit, user content from those subs doesn't show up in their profile *at all*.

Something that I've considered as a work-around for this is to maintain a bot whose account is opted into every single quarantined sub we can find, and PM the bot to request user history summaries. We can automate that process, though there will be some latency.

Otherwise, we would have to build a mass quarantine opt-in feature which would opt a mod account into every single quarantined sub that we know of. This is not ideal for a number of reasons, particularly the number of API requests required and the necessary introduced delay in the process.
