### ISSUE TITLE
Give proper feedback when trying to import settings when using localised URL

### ISSUE THREAD

**Issue by dClauzel** [creesch/reddit-moderator-toolbox#587]
Toolbox silently fails to import settings from a wiki when using Reddit with a localised URL such as “https://fr.reddit.com/”. Clicking on the “import” button has no effect.

Reloading Reddit from the URL “https://www.reddit.com/” then importing settings works fine.

This is a tricky behaviour: Toolbox should provides a warning when it fails to import settings.

**Comment by agentlame** [comment]
Sorry, this is by design.

**Comment by agentlame** [comment]
Oh, but you're correct that we are shit for giving proper feedback when you try to do so.   That *does* need to be fixed.  

BTW, in case you're wondering *why* it's 'by design' it has to do with how browsers treat subdomains and localStorage.   They consider different subdomains as different sites, which is a huge pain in the ass for reddit, but makes sense when you think of sites like tumblr or blogspot where subdomains *are* different sites.  

I'm going to reopen this to fix the lack of an error, but we can't do much about this issue itself.
