### ISSUE TITLE
When in /r/all the sub specific removal reasons are ignored when removing from a sub you mod

### ISSUE THREAD

**Issue by D0cR3d** [creesch/reddit-moderator-toolbox#604]
I was in /r/all, found a post I wanted to remove from a sub I mod (/r/InternetIsBeautiful) and we have custom removal reasons. I clicked the Remove option and it came up with the empty removal reason box, and not the sub specific removal reasons.

I DO have the setting enabled to show a empty removal reason box if there are no removal reasons configured.

Image: https://i.gyazo.com/f5e00cce497e411f9569861f2a83d45c.png

Toolbox settings backup: http://pastebin.com/EXcCru91

**Comment by agentlame** [comment]
Note to self and others, the fix for this likely lies here: https://github.com/creesch/reddit-moderator-toolbox/blob/master/tbutils.js#L10

Also, why do we do that on line 10 then this: https://github.com/creesch/reddit-moderator-toolbox/blob/master/tbutils.js#L118

I think we could clean those all into one big if.  Or maybe have and a array of invalid `post_site` vals and just do an `indexOf`.
