### ISSUE TITLE
template 'general' settings 

### ISSUE THREAD

**Issue by agentlame** [creesch/reddit-moderator-toolbox#607]
This shit is a joke, a mess, and a bitch to maintain: https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/modbar.js#L498

Each setting should be templated so we can support things like links to settings.  What would be even better would be to make those settings a sudo 'module', but I'm not sure of the best way to do that.

**Comment by Dakta** [comment]
This one is on me, as part of the final port to the module system. It's the last old-style settings UI. I haven't tackled it yet because it's architecturally tricky and will probably require rewriting a bunch of the modbar module. You're right that a bunch of meta stuff will have to be split out into another pseudo-module.

**Comment by Dakta** [comment]
I still don't quite know what the best approach for this is... I could make a fake module for it, but then we want to be able to do TB.setting() (at least, that's in the comments of tbmodule.js), and so that's two separate things.

Any thoughts? @agentlame @creesch
