### ISSUE TITLE
New settings:  Linking to a setting no longer turns that setting yellow.

### ISSUE THREAD

**Issue by creesch** [creesch/reddit-moderator-toolbox#632]
20:25 <agentlame> Linking to a setting no longer turns that setting yellow. :(   https://www.reddit.com#?tbsettings=rreasons&setting=alwaysshow
    20:25 <dakta> I don’t know how help links are supposed to work, but I’ll see if I can fix it. I’ve still got some other cleanup to do, but there are a few things that I don’t want to do like import/export.
    20:27 <creesch> dakta: afaik the help thing was really simple, just triggered the popup. Probably an easy fix. 
    20:27 <agentlame> dakta: https://github.com/creesch/reddit-moderator-toolbox/blob/master/modules/modbar.js#L716

**Comment by creesch** [comment]
@Dakta

**Comment by LiterallyWTH** [comment]
What did this used to look like?  Something like:

![THIS?!](http://i.imgur.com/tFaZT4F.png)

**Comment by creesch** [comment]
Yup pretty much

**Comment by LiterallyWTH** [comment]
Could it be because reddit strips the hashtag query off?  Check the url after the page loads: https://www.reddit.com#?tbsettings=rreasons&setting=alwaysshow

I'm going to bed but here's a solution I just sorta tested and it good:

Append the id of the element in question to the url hash (i.e. https://www.reddit.com#element_id) and you can select it with the css pseudo selector ':target' for styling.

**Comment by creesch** [comment]
Nah it is because of dakta refactoring settings and missing this :p

**Comment by agentlame** [comment]
>Could it be because reddit strips the hashtag query off? Check the url after the page loads: https://www.reddit.com#?tbsettings=rreasons&setting=alwaysshow

We do that, brah.  After we're sure it's a TB query.

**Comment by creesch** [comment]
It should be noted that @Dakta isn't to blame here (I think) but a committed change around the same time.
