### ISSUE TITLE
Allow moderators to set an alternate usernote repository for their subreddit, so that networks of subreddits can share usernotes

### ISSUE THREAD

**Issue by misterwoodhouse** [creesch/reddit-moderator-toolbox#694]
With so many video games having multiple subreddits managed by overlapping teams of moderators, many such groups have created formal networks for their game/franchise's subreddits. Fallout and Destiny are two such games.

For such networks, it would be very useful to have the option to select a central usernote location for the subreddits in question, allowing those usernotes to be shared across all the subreddits of the network. It would require all the moderators in the network to have wiki permissions on the subreddit used for the network's shared usernotes repository, but this would not be a big issue, as most such networks have private mod subs which would be perfect for this use case.

In terms of implementation, there could be an alternate usernotes repository field in the same settings panel as editing removal reasons, macros, etc. (the one in /mod/about/modqueue), in which a mod can set the alternate repository for their subreddit's usernotes, much like how it's done for personal notes.

**Comment by creesch** [comment]
This will never happen as this opens up a can of worms regarding people using toolbox as a meta tool rather than a mod tool.

**Comment by misterwoodhouse** [comment]
Could you explain that a bit more? I'm not sure I understand it completely.

**Comment by creesch** [comment]
Right, well in the past RES tags have been used by groups of people taking reddit waaaaaay to seriously. What they did is basically tag groups of users they didn't like for some reason and then export the RES tags and share them with a bunch of other people. 

We don't want to get involved in reddit's silly meta wars too much as toolbox is a moderation tool and nothing more. So in the past we always have said no to requests that make usernotes available outside the subs where they are stored. 
Implementing your feature would make it trivial for people to adjust in such a way that it worked across reddit regardless of subs modded.

We don't want that to happen, which is why such a feature will likely never be implemented.

**Comment by misterwoodhouse** [comment]
Well, that's certainly a very valid reason. Thanks for taking the time to clarify for me :+1: 

I guess we'll have to track our spammers the old fashioned way :)
