### ISSUE TITLE
Make Removal Reasons easier to discover 

### ISSUE THREAD

**Issue by Informalis** [creesch/reddit-moderator-toolbox#763]
Something I've (not?) discovered when trying to add a removal reason for one of the subreddits I moderate is where the dang configuration is.

I've accidentally stumbled across the option on the mod tool in the sidebar, however, a link to the settings in the Module Settings dialog would be very much appreciated.

I guess this could be generalized into discoverability for all user-editable settings.

**Comment by agentlame** [comment]
I suppose we could do that.  But it's not ideal, since sub settings are sub specific.   I should hope that anyone confused about how to configure removal reasons would consult the wiki.  Hell, the model settings for removal reasons even has that question mark window control that opens the wiki for removal reasons.

**Comment by creesch** [comment]
I agree with @agentlame, the subreddit specific settings are separated from the user specific settings for a very good reason. Even like it is now we often have people mixing them up and thinking they are both personal or vice versa. 

What we could do is something like android apps annoyingly do and do a "HEY LOOK YOU CAN DO STUFF OVER HERE" overlay on first run thingy. But considering how wide spread the usage is of toolbox and knowledge about it I don't really think it is needed. 

As a sidenote, you do know we have extensive documentation on the reddit wiki of toolbox? https://www.reddit.com/r/toolbox/wiki
