### ISSUE TITLE
Usernotes are broken when accessed from a subreddit-filtered user page

### ISSUE THREAD

**Issue by Geo1088** [creesch/reddit-moderator-toolbox#790]
Per [this thread](https://www.reddit.com/r/toolbox/comments/5h2y88/searching_for_comment_and_trying_to_add_note_fails/) because I actually never got around to looking at it myself.

If you use the "search by subreddit" feature in a user page, and then click the user notes dialog on any resulting post or comment, it doesn't work. I assume this is because the search result things aren't being constructed with the relevant `data-` attributes for author and/or subreddit. Could be wrong though, haven't looked at any code.

**Comment by creesch** [comment]
Oh that is entirely possible. We reconstruct the comment structure there but that format might be outdated. 

I was thinking about the other day actually, sometimes I wonder if it isn't "easier" to get the actual pages instead of going through the api so we can always be sure we have the correct html structure of the comments. The data overhead would be considerably more though I guess... 

So it is probably better to update our templates :)
