### ISSUE TITLE
Update notification cannot be dismissed

### ISSUE THREAD

**Issue by OverlordQ** [creesch/reddit-moderator-toolbox#842]
The update notification cannot be dismissed. 

Make something like RES where the icon glows or something. Overlaying a div that you can't get rid of is horrible UX.

**Comment by Geo1088** [comment]
The update notification is annoying by design.  Because subreddit Toolbox configs are shared among entire groups of users, one person on an old version of Toolbox can screw things up for all the other moderators of that person's subreddits. For that reason keeping the extension up-to-date is much more important than with an extension like RES, and so we make the update notification the way it is to make sure people are always running the latest version.
